### ISSUE TITLE
Library missing

### ISSUE THREAD

**Issue by mittalgovind** [likecs/Typeracer-CSF303-MiniProject#1]
<img width="484" alt="screen shot 2017-04-26 at 10 04 20 am" src="https://cloud.githubusercontent.com/assets/10897608/25418258/ddd66ed0-2a67-11e7-9aae-c1f67579d644.png">

**Comment by shubham-1996** [comment]
Install pthreads library and curses library. I will update the README.

**Comment by mittalgovind** [comment]
Thanks. I got it. You can close the issue now.
